name: Build 1.20.x

on:
  push:
    tags:
      - 'v*'

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Get Version
        id: version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            let ref = '${{ github.ref }}';
            return ref.startsWith('refs/tags/v') ? ref.replace('refs/tags/v', '') : 'indev';
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          VERSION: ${{ steps.version.outputs.result }}
      - name: Create Release
        id: create_release
        if: ${{ success() }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.result }}
          release_name: BetterFoliage v${{ steps.version.outputs.result }}
          body: |
            Version ${{ steps.version.outputs.result }}
            
            ### Changes
            
            - todo: document changes
          draft: true
      - name: Publish
        id: publish
        if: ${{ success() }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: curseforge
        env:
          VERSION: ${{ steps.version.outputs.result }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
